// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module swapcmp (
        ap_ready,
        a_read,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [31:0] a_read;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

assign ap_ready = 1'b1;

assign ap_return_0 = a_read;

assign ap_return_1 = a_read;

endmodule //swapcmp
