webtalk_init -webtalk_dir /home/rbeaubois/Documents/ENSEIRB/Sorting-algorithms/vivado/pynq/pynq.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-21 11:45:32" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "420ojcf0u4l1qlnntof39m8h42" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1897.993 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8,182 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1579602957000" -context "sdk\\\\bsp/1579602957000"
webtalk_add_data -client sdk -key hwid -value "1579602634000" -context "sdk\\\\bsp/1579602957000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1579602957000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1579602957000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1579602957000"
webtalk_add_data -client sdk -key uid -value "1579602959000" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key hwid -value "1579602634000" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key bspid -value "1579602957000" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key projSize -value "398.42578125" -context "sdk\\\\application/1579602959000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1579603532348"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1579603532348"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1579603532348"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1579603532348"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1579603532348"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1579603532348"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1579603532348"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1579603532348"
webtalk_transmit -clientid 3873890176 -regid "" -xml /home/rbeaubois/Documents/ENSEIRB/Sorting-algorithms/vivado/pynq/pynq.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/rbeaubois/Documents/ENSEIRB/Sorting-algorithms/vivado/pynq/pynq.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/rbeaubois/Documents/ENSEIRB/Sorting-algorithms/vivado/pynq/pynq.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
