// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="HLS_radix,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.674000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=264,HLS_SYN_DSP=0,HLS_SYN_FF=885,HLS_SYN_LUT=2375,HLS_VERSION=2018_2}" *)

module HLS_radix (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TUSER,
        S_AXIS_TLAST,
        S_AXIS_TID,
        S_AXIS_TDEST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TUSER,
        M_AXIS_TLAST,
        M_AXIS_TID,
        M_AXIS_TDEST
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TUSER;
input  [0:0] S_AXIS_TLAST;
input  [0:0] S_AXIS_TID;
input  [0:0] S_AXIS_TDEST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TUSER;
output  [0:0] M_AXIS_TLAST;
output  [0:0] M_AXIS_TID;
output  [0:0] M_AXIS_TDEST;

 reg    ap_rst_n_inv;
reg   [31:0] S_AXIS_V_data_V_0_data_out;
wire    S_AXIS_V_data_V_0_vld_in;
wire    S_AXIS_V_data_V_0_vld_out;
wire    S_AXIS_V_data_V_0_ack_in;
reg    S_AXIS_V_data_V_0_ack_out;
reg   [31:0] S_AXIS_V_data_V_0_payload_A;
reg   [31:0] S_AXIS_V_data_V_0_payload_B;
reg    S_AXIS_V_data_V_0_sel_rd;
reg    S_AXIS_V_data_V_0_sel_wr;
wire    S_AXIS_V_data_V_0_sel;
wire    S_AXIS_V_data_V_0_load_A;
wire    S_AXIS_V_data_V_0_load_B;
reg   [1:0] S_AXIS_V_data_V_0_state;
wire    S_AXIS_V_data_V_0_state_cmp_full;
reg   [3:0] S_AXIS_V_keep_V_0_data_out;
wire    S_AXIS_V_keep_V_0_vld_in;
wire    S_AXIS_V_keep_V_0_vld_out;
wire    S_AXIS_V_keep_V_0_ack_in;
reg    S_AXIS_V_keep_V_0_ack_out;
reg   [3:0] S_AXIS_V_keep_V_0_payload_A;
reg   [3:0] S_AXIS_V_keep_V_0_payload_B;
reg    S_AXIS_V_keep_V_0_sel_rd;
reg    S_AXIS_V_keep_V_0_sel_wr;
wire    S_AXIS_V_keep_V_0_sel;
wire    S_AXIS_V_keep_V_0_load_A;
wire    S_AXIS_V_keep_V_0_load_B;
reg   [1:0] S_AXIS_V_keep_V_0_state;
wire    S_AXIS_V_keep_V_0_state_cmp_full;
reg   [3:0] S_AXIS_V_strb_V_0_data_out;
wire    S_AXIS_V_strb_V_0_vld_in;
wire    S_AXIS_V_strb_V_0_vld_out;
wire    S_AXIS_V_strb_V_0_ack_in;
reg    S_AXIS_V_strb_V_0_ack_out;
reg   [3:0] S_AXIS_V_strb_V_0_payload_A;
reg   [3:0] S_AXIS_V_strb_V_0_payload_B;
reg    S_AXIS_V_strb_V_0_sel_rd;
reg    S_AXIS_V_strb_V_0_sel_wr;
wire    S_AXIS_V_strb_V_0_sel;
wire    S_AXIS_V_strb_V_0_load_A;
wire    S_AXIS_V_strb_V_0_load_B;
reg   [1:0] S_AXIS_V_strb_V_0_state;
wire    S_AXIS_V_strb_V_0_state_cmp_full;
reg   [0:0] S_AXIS_V_user_V_0_data_out;
wire    S_AXIS_V_user_V_0_vld_in;
wire    S_AXIS_V_user_V_0_vld_out;
wire    S_AXIS_V_user_V_0_ack_in;
reg    S_AXIS_V_user_V_0_ack_out;
reg   [0:0] S_AXIS_V_user_V_0_payload_A;
reg   [0:0] S_AXIS_V_user_V_0_payload_B;
reg    S_AXIS_V_user_V_0_sel_rd;
reg    S_AXIS_V_user_V_0_sel_wr;
wire    S_AXIS_V_user_V_0_sel;
wire    S_AXIS_V_user_V_0_load_A;
wire    S_AXIS_V_user_V_0_load_B;
reg   [1:0] S_AXIS_V_user_V_0_state;
wire    S_AXIS_V_user_V_0_state_cmp_full;
reg   [0:0] S_AXIS_V_id_V_0_data_out;
wire    S_AXIS_V_id_V_0_vld_in;
wire    S_AXIS_V_id_V_0_vld_out;
wire    S_AXIS_V_id_V_0_ack_in;
reg    S_AXIS_V_id_V_0_ack_out;
reg   [0:0] S_AXIS_V_id_V_0_payload_A;
reg   [0:0] S_AXIS_V_id_V_0_payload_B;
reg    S_AXIS_V_id_V_0_sel_rd;
reg    S_AXIS_V_id_V_0_sel_wr;
wire    S_AXIS_V_id_V_0_sel;
wire    S_AXIS_V_id_V_0_load_A;
wire    S_AXIS_V_id_V_0_load_B;
reg   [1:0] S_AXIS_V_id_V_0_state;
wire    S_AXIS_V_id_V_0_state_cmp_full;
reg   [0:0] S_AXIS_V_dest_V_0_data_out;
wire    S_AXIS_V_dest_V_0_vld_in;
wire    S_AXIS_V_dest_V_0_vld_out;
wire    S_AXIS_V_dest_V_0_ack_in;
reg    S_AXIS_V_dest_V_0_ack_out;
reg   [0:0] S_AXIS_V_dest_V_0_payload_A;
reg   [0:0] S_AXIS_V_dest_V_0_payload_B;
reg    S_AXIS_V_dest_V_0_sel_rd;
reg    S_AXIS_V_dest_V_0_sel_wr;
wire    S_AXIS_V_dest_V_0_sel;
wire    S_AXIS_V_dest_V_0_load_A;
wire    S_AXIS_V_dest_V_0_load_B;
reg   [1:0] S_AXIS_V_dest_V_0_state;
wire    S_AXIS_V_dest_V_0_state_cmp_full;
reg   [31:0] M_AXIS_V_data_V_1_data_out;
reg    M_AXIS_V_data_V_1_vld_in;
wire    M_AXIS_V_data_V_1_vld_out;
wire    M_AXIS_V_data_V_1_ack_in;
wire    M_AXIS_V_data_V_1_ack_out;
reg   [31:0] M_AXIS_V_data_V_1_payload_A;
reg   [31:0] M_AXIS_V_data_V_1_payload_B;
reg    M_AXIS_V_data_V_1_sel_rd;
reg    M_AXIS_V_data_V_1_sel_wr;
wire    M_AXIS_V_data_V_1_sel;
wire    M_AXIS_V_data_V_1_load_A;
wire    M_AXIS_V_data_V_1_load_B;
reg   [1:0] M_AXIS_V_data_V_1_state;
wire    M_AXIS_V_data_V_1_state_cmp_full;
reg   [3:0] M_AXIS_V_keep_V_1_data_out;
reg    M_AXIS_V_keep_V_1_vld_in;
wire    M_AXIS_V_keep_V_1_vld_out;
wire    M_AXIS_V_keep_V_1_ack_in;
wire    M_AXIS_V_keep_V_1_ack_out;
reg   [3:0] M_AXIS_V_keep_V_1_payload_A;
reg   [3:0] M_AXIS_V_keep_V_1_payload_B;
reg    M_AXIS_V_keep_V_1_sel_rd;
reg    M_AXIS_V_keep_V_1_sel_wr;
wire    M_AXIS_V_keep_V_1_sel;
wire    M_AXIS_V_keep_V_1_load_A;
wire    M_AXIS_V_keep_V_1_load_B;
reg   [1:0] M_AXIS_V_keep_V_1_state;
wire    M_AXIS_V_keep_V_1_state_cmp_full;
reg   [3:0] M_AXIS_V_strb_V_1_data_out;
reg    M_AXIS_V_strb_V_1_vld_in;
wire    M_AXIS_V_strb_V_1_vld_out;
wire    M_AXIS_V_strb_V_1_ack_in;
wire    M_AXIS_V_strb_V_1_ack_out;
reg   [3:0] M_AXIS_V_strb_V_1_payload_A;
reg   [3:0] M_AXIS_V_strb_V_1_payload_B;
reg    M_AXIS_V_strb_V_1_sel_rd;
reg    M_AXIS_V_strb_V_1_sel_wr;
wire    M_AXIS_V_strb_V_1_sel;
wire    M_AXIS_V_strb_V_1_load_A;
wire    M_AXIS_V_strb_V_1_load_B;
reg   [1:0] M_AXIS_V_strb_V_1_state;
wire    M_AXIS_V_strb_V_1_state_cmp_full;
reg   [0:0] M_AXIS_V_user_V_1_data_out;
reg    M_AXIS_V_user_V_1_vld_in;
wire    M_AXIS_V_user_V_1_vld_out;
wire    M_AXIS_V_user_V_1_ack_in;
wire    M_AXIS_V_user_V_1_ack_out;
reg   [0:0] M_AXIS_V_user_V_1_payload_A;
reg   [0:0] M_AXIS_V_user_V_1_payload_B;
reg    M_AXIS_V_user_V_1_sel_rd;
reg    M_AXIS_V_user_V_1_sel_wr;
wire    M_AXIS_V_user_V_1_sel;
wire    M_AXIS_V_user_V_1_load_A;
wire    M_AXIS_V_user_V_1_load_B;
reg   [1:0] M_AXIS_V_user_V_1_state;
wire    M_AXIS_V_user_V_1_state_cmp_full;
reg   [0:0] M_AXIS_V_last_V_1_data_out;
reg    M_AXIS_V_last_V_1_vld_in;
wire    M_AXIS_V_last_V_1_vld_out;
wire    M_AXIS_V_last_V_1_ack_in;
wire    M_AXIS_V_last_V_1_ack_out;
reg   [0:0] M_AXIS_V_last_V_1_payload_A;
reg   [0:0] M_AXIS_V_last_V_1_payload_B;
reg    M_AXIS_V_last_V_1_sel_rd;
reg    M_AXIS_V_last_V_1_sel_wr;
wire    M_AXIS_V_last_V_1_sel;
wire    M_AXIS_V_last_V_1_load_A;
wire    M_AXIS_V_last_V_1_load_B;
reg   [1:0] M_AXIS_V_last_V_1_state;
wire    M_AXIS_V_last_V_1_state_cmp_full;
reg   [0:0] M_AXIS_V_id_V_1_data_out;
reg    M_AXIS_V_id_V_1_vld_in;
wire    M_AXIS_V_id_V_1_vld_out;
wire    M_AXIS_V_id_V_1_ack_in;
wire    M_AXIS_V_id_V_1_ack_out;
reg   [0:0] M_AXIS_V_id_V_1_payload_A;
reg   [0:0] M_AXIS_V_id_V_1_payload_B;
reg    M_AXIS_V_id_V_1_sel_rd;
reg    M_AXIS_V_id_V_1_sel_wr;
wire    M_AXIS_V_id_V_1_sel;
wire    M_AXIS_V_id_V_1_load_A;
wire    M_AXIS_V_id_V_1_load_B;
reg   [1:0] M_AXIS_V_id_V_1_state;
wire    M_AXIS_V_id_V_1_state_cmp_full;
reg   [0:0] M_AXIS_V_dest_V_1_data_out;
reg    M_AXIS_V_dest_V_1_vld_in;
wire    M_AXIS_V_dest_V_1_vld_out;
wire    M_AXIS_V_dest_V_1_ack_in;
wire    M_AXIS_V_dest_V_1_ack_out;
reg   [0:0] M_AXIS_V_dest_V_1_payload_A;
reg   [0:0] M_AXIS_V_dest_V_1_payload_B;
reg    M_AXIS_V_dest_V_1_sel_rd;
reg    M_AXIS_V_dest_V_1_sel_wr;
wire    M_AXIS_V_dest_V_1_sel;
wire    M_AXIS_V_dest_V_1_load_A;
wire    M_AXIS_V_dest_V_1_load_B;
reg   [1:0] M_AXIS_V_dest_V_1_state;
wire    M_AXIS_V_dest_V_1_state_cmp_full;
reg    S_AXIS_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state5;
reg    M_AXIS_TDATA_blk_n;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire   [15:0] indvarinc_fu_387_p2;
wire    ap_CS_fsm_state2;
wire   [16:0] i_4_fu_410_p2;
reg   [16:0] i_4_reg_629;
wire    ap_CS_fsm_state4;
wire   [7:0] indvarinc_i_fu_471_p2;
wire    ap_CS_fsm_state6;
wire   [7:0] indvarinc3_i_fu_488_p2;
wire    ap_CS_fsm_state7;
wire   [7:0] indvarinc6_i_fu_505_p2;
wire    ap_CS_fsm_state8;
wire   [7:0] indvarinc9_i_fu_522_p2;
wire    ap_CS_fsm_state9;
wire   [16:0] i_5_fu_545_p2;
reg   [16:0] i_5_reg_669;
wire    ap_CS_fsm_state20;
wire   [0:0] exitcond_fu_539_p2;
wire   [0:0] tmp_last_V_fu_562_p2;
reg   [0:0] tmp_last_V_reg_679;
wire   [31:0] tab_q0;
reg   [15:0] array2_address0;
reg    array2_ce0;
reg    array2_we0;
wire   [31:0] array2_q0;
reg   [7:0] count_1_address0;
reg    count_1_ce0;
reg    count_1_we0;
reg   [31:0] count_1_d0;
wire   [31:0] count_1_q0;
reg    count_1_ce1;
reg    count_1_we1;
wire   [31:0] count_1_q1;
reg   [7:0] count_2_address0;
reg    count_2_ce0;
reg    count_2_we0;
reg   [31:0] count_2_d0;
wire   [31:0] count_2_q0;
reg    count_2_ce1;
reg    count_2_we1;
wire   [31:0] count_2_q1;
reg   [7:0] count_3_address0;
reg    count_3_ce0;
reg    count_3_we0;
reg   [31:0] count_3_d0;
wire   [31:0] count_3_q0;
reg    count_3_ce1;
reg    count_3_we1;
wire   [31:0] count_3_q1;
reg   [7:0] count_4_address0;
reg    count_4_ce0;
reg    count_4_we0;
reg   [31:0] count_4_d0;
wire   [31:0] count_4_q0;
reg    count_4_ce1;
reg    count_4_we1;
wire   [31:0] count_4_q1;
reg   [15:0] tab_address0;
reg    tab_ce0;
reg    tab_we0;
reg   [31:0] tab_d0;
wire    grp_count_occ_v2_fu_366_ap_start;
wire    grp_count_occ_v2_fu_366_ap_done;
wire    grp_count_occ_v2_fu_366_ap_idle;
wire    grp_count_occ_v2_fu_366_ap_ready;
wire   [15:0] grp_count_occ_v2_fu_366_array_src_address0;
wire    grp_count_occ_v2_fu_366_array_src_ce0;
wire   [7:0] grp_count_occ_v2_fu_366_c1_address0;
wire    grp_count_occ_v2_fu_366_c1_ce0;
wire    grp_count_occ_v2_fu_366_c1_we0;
wire   [31:0] grp_count_occ_v2_fu_366_c1_d0;
wire   [7:0] grp_count_occ_v2_fu_366_c1_address1;
wire    grp_count_occ_v2_fu_366_c1_ce1;
wire    grp_count_occ_v2_fu_366_c1_we1;
wire   [31:0] grp_count_occ_v2_fu_366_c1_d1;
wire   [7:0] grp_count_occ_v2_fu_366_c2_address0;
wire    grp_count_occ_v2_fu_366_c2_ce0;
wire    grp_count_occ_v2_fu_366_c2_we0;
wire   [31:0] grp_count_occ_v2_fu_366_c2_d0;
wire   [7:0] grp_count_occ_v2_fu_366_c2_address1;
wire    grp_count_occ_v2_fu_366_c2_ce1;
wire    grp_count_occ_v2_fu_366_c2_we1;
wire   [31:0] grp_count_occ_v2_fu_366_c2_d1;
wire   [7:0] grp_count_occ_v2_fu_366_c3_address0;
wire    grp_count_occ_v2_fu_366_c3_ce0;
wire    grp_count_occ_v2_fu_366_c3_we0;
wire   [31:0] grp_count_occ_v2_fu_366_c3_d0;
wire   [7:0] grp_count_occ_v2_fu_366_c3_address1;
wire    grp_count_occ_v2_fu_366_c3_ce1;
wire    grp_count_occ_v2_fu_366_c3_we1;
wire   [31:0] grp_count_occ_v2_fu_366_c3_d1;
wire   [7:0] grp_count_occ_v2_fu_366_c4_address0;
wire    grp_count_occ_v2_fu_366_c4_ce0;
wire    grp_count_occ_v2_fu_366_c4_we0;
wire   [31:0] grp_count_occ_v2_fu_366_c4_d0;
wire   [7:0] grp_count_occ_v2_fu_366_c4_address1;
wire    grp_count_occ_v2_fu_366_c4_ce1;
wire    grp_count_occ_v2_fu_366_c4_we1;
wire   [31:0] grp_count_occ_v2_fu_366_c4_d1;
wire    grp_sort_occ_v2_fu_375_ap_start;
wire    grp_sort_occ_v2_fu_375_ap_done;
wire    grp_sort_occ_v2_fu_375_ap_idle;
wire    grp_sort_occ_v2_fu_375_ap_ready;
wire   [15:0] grp_sort_occ_v2_fu_375_array_src_address0;
wire    grp_sort_occ_v2_fu_375_array_src_ce0;
reg   [31:0] grp_sort_occ_v2_fu_375_array_src_q0;
wire   [15:0] grp_sort_occ_v2_fu_375_array_dst_address0;
wire    grp_sort_occ_v2_fu_375_array_dst_ce0;
wire    grp_sort_occ_v2_fu_375_array_dst_we0;
wire   [31:0] grp_sort_occ_v2_fu_375_array_dst_d0;
reg   [5:0] grp_sort_occ_v2_fu_375_shift;
wire   [7:0] grp_sort_occ_v2_fu_375_count_address0;
wire    grp_sort_occ_v2_fu_375_count_ce0;
wire    grp_sort_occ_v2_fu_375_count_we0;
wire   [31:0] grp_sort_occ_v2_fu_375_count_d0;
reg   [31:0] grp_sort_occ_v2_fu_375_count_q0;
reg   [15:0] invdar_reg_277;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_s_fu_398_p2;
reg   [16:0] i_reg_288;
wire    ap_CS_fsm_state3;
reg   [7:0] invdar_i_reg_300;
wire   [0:0] tmp_i_16_fu_482_p2;
wire   [0:0] exitcond1_fu_404_p2;
reg   [7:0] invdar2_i_reg_311;
wire   [0:0] tmp_2_i_fu_499_p2;
reg   [7:0] invdar5_i_reg_322;
wire   [0:0] tmp_4_i_fu_516_p2;
reg   [7:0] invdar8_i_reg_333;
wire   [0:0] tmp_6_i_fu_533_p2;
reg   [0:0] val_4_reg_344;
wire    ap_CS_fsm_state19;
reg   [16:0] i_1_reg_355;
reg    grp_count_occ_v2_fu_366_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_sort_occ_v2_fu_375_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state17;
wire   [63:0] tmp_fu_393_p1;
wire   [63:0] tmp_16_fu_441_p1;
wire   [63:0] tmp_i_fu_477_p1;
wire   [63:0] tmp_1_i_fu_494_p1;
wire   [63:0] tmp_3_i_fu_511_p1;
wire   [63:0] tmp_5_i_fu_528_p1;
wire   [63:0] tmp_17_fu_551_p1;
reg   [3:0] tmp_keep_V_fu_134;
reg   [3:0] tmp_strb_V_fu_138;
reg   [0:0] tmp_user_V_fu_142;
reg   [0:0] tmp_id_V_fu_146;
reg   [0:0] tmp_dest_V_fu_150;
wire   [0:0] tmp_18_fu_556_p2;
reg   [21:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 S_AXIS_V_data_V_0_sel_rd = 1'b0;
#0 S_AXIS_V_data_V_0_sel_wr = 1'b0;
#0 S_AXIS_V_data_V_0_state = 2'd0;
#0 S_AXIS_V_keep_V_0_sel_rd = 1'b0;
#0 S_AXIS_V_keep_V_0_sel_wr = 1'b0;
#0 S_AXIS_V_keep_V_0_state = 2'd0;
#0 S_AXIS_V_strb_V_0_sel_rd = 1'b0;
#0 S_AXIS_V_strb_V_0_sel_wr = 1'b0;
#0 S_AXIS_V_strb_V_0_state = 2'd0;
#0 S_AXIS_V_user_V_0_sel_rd = 1'b0;
#0 S_AXIS_V_user_V_0_sel_wr = 1'b0;
#0 S_AXIS_V_user_V_0_state = 2'd0;
#0 S_AXIS_V_id_V_0_sel_rd = 1'b0;
#0 S_AXIS_V_id_V_0_sel_wr = 1'b0;
#0 S_AXIS_V_id_V_0_state = 2'd0;
#0 S_AXIS_V_dest_V_0_sel_rd = 1'b0;
#0 S_AXIS_V_dest_V_0_sel_wr = 1'b0;
#0 S_AXIS_V_dest_V_0_state = 2'd0;
#0 M_AXIS_V_data_V_1_sel_rd = 1'b0;
#0 M_AXIS_V_data_V_1_sel_wr = 1'b0;
#0 M_AXIS_V_data_V_1_state = 2'd0;
#0 M_AXIS_V_keep_V_1_sel_rd = 1'b0;
#0 M_AXIS_V_keep_V_1_sel_wr = 1'b0;
#0 M_AXIS_V_keep_V_1_state = 2'd0;
#0 M_AXIS_V_strb_V_1_sel_rd = 1'b0;
#0 M_AXIS_V_strb_V_1_sel_wr = 1'b0;
#0 M_AXIS_V_strb_V_1_state = 2'd0;
#0 M_AXIS_V_user_V_1_sel_rd = 1'b0;
#0 M_AXIS_V_user_V_1_sel_wr = 1'b0;
#0 M_AXIS_V_user_V_1_state = 2'd0;
#0 M_AXIS_V_last_V_1_sel_rd = 1'b0;
#0 M_AXIS_V_last_V_1_sel_wr = 1'b0;
#0 M_AXIS_V_last_V_1_state = 2'd0;
#0 M_AXIS_V_id_V_1_sel_rd = 1'b0;
#0 M_AXIS_V_id_V_1_sel_wr = 1'b0;
#0 M_AXIS_V_id_V_1_state = 2'd0;
#0 M_AXIS_V_dest_V_1_sel_rd = 1'b0;
#0 M_AXIS_V_dest_V_1_sel_wr = 1'b0;
#0 M_AXIS_V_dest_V_1_state = 2'd0;
#0 ap_CS_fsm = 22'd1;
#0 grp_count_occ_v2_fu_366_ap_start_reg = 1'b0;
#0 grp_sort_occ_v2_fu_375_ap_start_reg = 1'b0;
end

HLS_radix_array2 #(
    .DataWidth( 32 ),
    .AddressRange( 65536 ),
    .AddressWidth( 16 ))
array2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(array2_address0),
    .ce0(array2_ce0),
    .we0(array2_we0),
    .d0(grp_sort_occ_v2_fu_375_array_dst_d0),
    .q0(array2_q0)
);

HLS_radix_count_1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
count_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(count_1_address0),
    .ce0(count_1_ce0),
    .we0(count_1_we0),
    .d0(count_1_d0),
    .q0(count_1_q0),
    .address1(grp_count_occ_v2_fu_366_c1_address1),
    .ce1(count_1_ce1),
    .we1(count_1_we1),
    .d1(grp_count_occ_v2_fu_366_c1_d1),
    .q1(count_1_q1)
);

HLS_radix_count_1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
count_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(count_2_address0),
    .ce0(count_2_ce0),
    .we0(count_2_we0),
    .d0(count_2_d0),
    .q0(count_2_q0),
    .address1(grp_count_occ_v2_fu_366_c2_address1),
    .ce1(count_2_ce1),
    .we1(count_2_we1),
    .d1(grp_count_occ_v2_fu_366_c2_d1),
    .q1(count_2_q1)
);

HLS_radix_count_1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
count_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(count_3_address0),
    .ce0(count_3_ce0),
    .we0(count_3_we0),
    .d0(count_3_d0),
    .q0(count_3_q0),
    .address1(grp_count_occ_v2_fu_366_c3_address1),
    .ce1(count_3_ce1),
    .we1(count_3_we1),
    .d1(grp_count_occ_v2_fu_366_c3_d1),
    .q1(count_3_q1)
);

HLS_radix_count_1 #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
count_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(count_4_address0),
    .ce0(count_4_ce0),
    .we0(count_4_we0),
    .d0(count_4_d0),
    .q0(count_4_q0),
    .address1(grp_count_occ_v2_fu_366_c4_address1),
    .ce1(count_4_ce1),
    .we1(count_4_we1),
    .d1(grp_count_occ_v2_fu_366_c4_d1),
    .q1(count_4_q1)
);

HLS_radix_array2 #(
    .DataWidth( 32 ),
    .AddressRange( 65536 ),
    .AddressWidth( 16 ))
tab_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(tab_address0),
    .ce0(tab_ce0),
    .we0(tab_we0),
    .d0(tab_d0),
    .q0(tab_q0)
);

count_occ_v2 grp_count_occ_v2_fu_366(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_count_occ_v2_fu_366_ap_start),
    .ap_done(grp_count_occ_v2_fu_366_ap_done),
    .ap_idle(grp_count_occ_v2_fu_366_ap_idle),
    .ap_ready(grp_count_occ_v2_fu_366_ap_ready),
    .array_src_address0(grp_count_occ_v2_fu_366_array_src_address0),
    .array_src_ce0(grp_count_occ_v2_fu_366_array_src_ce0),
    .array_src_q0(tab_q0),
    .c1_address0(grp_count_occ_v2_fu_366_c1_address0),
    .c1_ce0(grp_count_occ_v2_fu_366_c1_ce0),
    .c1_we0(grp_count_occ_v2_fu_366_c1_we0),
    .c1_d0(grp_count_occ_v2_fu_366_c1_d0),
    .c1_q0(count_1_q0),
    .c1_address1(grp_count_occ_v2_fu_366_c1_address1),
    .c1_ce1(grp_count_occ_v2_fu_366_c1_ce1),
    .c1_we1(grp_count_occ_v2_fu_366_c1_we1),
    .c1_d1(grp_count_occ_v2_fu_366_c1_d1),
    .c1_q1(count_1_q1),
    .c2_address0(grp_count_occ_v2_fu_366_c2_address0),
    .c2_ce0(grp_count_occ_v2_fu_366_c2_ce0),
    .c2_we0(grp_count_occ_v2_fu_366_c2_we0),
    .c2_d0(grp_count_occ_v2_fu_366_c2_d0),
    .c2_q0(count_2_q0),
    .c2_address1(grp_count_occ_v2_fu_366_c2_address1),
    .c2_ce1(grp_count_occ_v2_fu_366_c2_ce1),
    .c2_we1(grp_count_occ_v2_fu_366_c2_we1),
    .c2_d1(grp_count_occ_v2_fu_366_c2_d1),
    .c2_q1(count_2_q1),
    .c3_address0(grp_count_occ_v2_fu_366_c3_address0),
    .c3_ce0(grp_count_occ_v2_fu_366_c3_ce0),
    .c3_we0(grp_count_occ_v2_fu_366_c3_we0),
    .c3_d0(grp_count_occ_v2_fu_366_c3_d0),
    .c3_q0(count_3_q0),
    .c3_address1(grp_count_occ_v2_fu_366_c3_address1),
    .c3_ce1(grp_count_occ_v2_fu_366_c3_ce1),
    .c3_we1(grp_count_occ_v2_fu_366_c3_we1),
    .c3_d1(grp_count_occ_v2_fu_366_c3_d1),
    .c3_q1(count_3_q1),
    .c4_address0(grp_count_occ_v2_fu_366_c4_address0),
    .c4_ce0(grp_count_occ_v2_fu_366_c4_ce0),
    .c4_we0(grp_count_occ_v2_fu_366_c4_we0),
    .c4_d0(grp_count_occ_v2_fu_366_c4_d0),
    .c4_q0(count_4_q0),
    .c4_address1(grp_count_occ_v2_fu_366_c4_address1),
    .c4_ce1(grp_count_occ_v2_fu_366_c4_ce1),
    .c4_we1(grp_count_occ_v2_fu_366_c4_we1),
    .c4_d1(grp_count_occ_v2_fu_366_c4_d1),
    .c4_q1(count_4_q1)
);

sort_occ_v2 grp_sort_occ_v2_fu_375(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sort_occ_v2_fu_375_ap_start),
    .ap_done(grp_sort_occ_v2_fu_375_ap_done),
    .ap_idle(grp_sort_occ_v2_fu_375_ap_idle),
    .ap_ready(grp_sort_occ_v2_fu_375_ap_ready),
    .array_src_address0(grp_sort_occ_v2_fu_375_array_src_address0),
    .array_src_ce0(grp_sort_occ_v2_fu_375_array_src_ce0),
    .array_src_q0(grp_sort_occ_v2_fu_375_array_src_q0),
    .array_dst_address0(grp_sort_occ_v2_fu_375_array_dst_address0),
    .array_dst_ce0(grp_sort_occ_v2_fu_375_array_dst_ce0),
    .array_dst_we0(grp_sort_occ_v2_fu_375_array_dst_we0),
    .array_dst_d0(grp_sort_occ_v2_fu_375_array_dst_d0),
    .shift(grp_sort_occ_v2_fu_375_shift),
    .count_address0(grp_sort_occ_v2_fu_375_count_address0),
    .count_ce0(grp_sort_occ_v2_fu_375_count_ce0),
    .count_we0(grp_sort_occ_v2_fu_375_count_we0),
    .count_d0(grp_sort_occ_v2_fu_375_count_d0),
    .count_q0(grp_sort_occ_v2_fu_375_count_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_data_V_1_ack_out) & (1'b1 == M_AXIS_V_data_V_1_vld_out))) begin
            M_AXIS_V_data_V_1_sel_rd <= ~M_AXIS_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == M_AXIS_V_data_V_1_vld_in))) begin
            M_AXIS_V_data_V_1_sel_wr <= ~M_AXIS_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == M_AXIS_V_data_V_1_state) & (1'b0 == M_AXIS_V_data_V_1_vld_in)) | ((2'd3 == M_AXIS_V_data_V_1_state) & (1'b0 == M_AXIS_V_data_V_1_vld_in) & (1'b1 == M_AXIS_V_data_V_1_ack_out)))) begin
            M_AXIS_V_data_V_1_state <= 2'd2;
        end else if ((((2'd1 == M_AXIS_V_data_V_1_state) & (1'b0 == M_AXIS_V_data_V_1_ack_out)) | ((2'd3 == M_AXIS_V_data_V_1_state) & (1'b0 == M_AXIS_V_data_V_1_ack_out) & (1'b1 == M_AXIS_V_data_V_1_vld_in)))) begin
            M_AXIS_V_data_V_1_state <= 2'd1;
        end else if (((~((1'b0 == M_AXIS_V_data_V_1_vld_in) & (1'b1 == M_AXIS_V_data_V_1_ack_out)) & ~((1'b0 == M_AXIS_V_data_V_1_ack_out) & (1'b1 == M_AXIS_V_data_V_1_vld_in)) & (2'd3 == M_AXIS_V_data_V_1_state)) | ((2'd1 == M_AXIS_V_data_V_1_state) & (1'b1 == M_AXIS_V_data_V_1_ack_out)) | ((2'd2 == M_AXIS_V_data_V_1_state) & (1'b1 == M_AXIS_V_data_V_1_vld_in)))) begin
            M_AXIS_V_data_V_1_state <= 2'd3;
        end else begin
            M_AXIS_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_dest_V_1_ack_out) & (1'b1 == M_AXIS_V_dest_V_1_vld_out))) begin
            M_AXIS_V_dest_V_1_sel_rd <= ~M_AXIS_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_dest_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_dest_V_1_ack_in) & (1'b1 == M_AXIS_V_dest_V_1_vld_in))) begin
            M_AXIS_V_dest_V_1_sel_wr <= ~M_AXIS_V_dest_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == M_AXIS_V_dest_V_1_state) & (1'b0 == M_AXIS_V_dest_V_1_vld_in)) | ((2'd3 == M_AXIS_V_dest_V_1_state) & (1'b0 == M_AXIS_V_dest_V_1_vld_in) & (1'b1 == M_AXIS_V_dest_V_1_ack_out)))) begin
            M_AXIS_V_dest_V_1_state <= 2'd2;
        end else if ((((2'd1 == M_AXIS_V_dest_V_1_state) & (1'b0 == M_AXIS_V_dest_V_1_ack_out)) | ((2'd3 == M_AXIS_V_dest_V_1_state) & (1'b0 == M_AXIS_V_dest_V_1_ack_out) & (1'b1 == M_AXIS_V_dest_V_1_vld_in)))) begin
            M_AXIS_V_dest_V_1_state <= 2'd1;
        end else if (((~((1'b0 == M_AXIS_V_dest_V_1_vld_in) & (1'b1 == M_AXIS_V_dest_V_1_ack_out)) & ~((1'b0 == M_AXIS_V_dest_V_1_ack_out) & (1'b1 == M_AXIS_V_dest_V_1_vld_in)) & (2'd3 == M_AXIS_V_dest_V_1_state)) | ((2'd1 == M_AXIS_V_dest_V_1_state) & (1'b1 == M_AXIS_V_dest_V_1_ack_out)) | ((2'd2 == M_AXIS_V_dest_V_1_state) & (1'b1 == M_AXIS_V_dest_V_1_vld_in)))) begin
            M_AXIS_V_dest_V_1_state <= 2'd3;
        end else begin
            M_AXIS_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_id_V_1_ack_out) & (1'b1 == M_AXIS_V_id_V_1_vld_out))) begin
            M_AXIS_V_id_V_1_sel_rd <= ~M_AXIS_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_id_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_id_V_1_ack_in) & (1'b1 == M_AXIS_V_id_V_1_vld_in))) begin
            M_AXIS_V_id_V_1_sel_wr <= ~M_AXIS_V_id_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == M_AXIS_V_id_V_1_state) & (1'b0 == M_AXIS_V_id_V_1_vld_in)) | ((2'd3 == M_AXIS_V_id_V_1_state) & (1'b0 == M_AXIS_V_id_V_1_vld_in) & (1'b1 == M_AXIS_V_id_V_1_ack_out)))) begin
            M_AXIS_V_id_V_1_state <= 2'd2;
        end else if ((((2'd1 == M_AXIS_V_id_V_1_state) & (1'b0 == M_AXIS_V_id_V_1_ack_out)) | ((2'd3 == M_AXIS_V_id_V_1_state) & (1'b0 == M_AXIS_V_id_V_1_ack_out) & (1'b1 == M_AXIS_V_id_V_1_vld_in)))) begin
            M_AXIS_V_id_V_1_state <= 2'd1;
        end else if (((~((1'b0 == M_AXIS_V_id_V_1_vld_in) & (1'b1 == M_AXIS_V_id_V_1_ack_out)) & ~((1'b0 == M_AXIS_V_id_V_1_ack_out) & (1'b1 == M_AXIS_V_id_V_1_vld_in)) & (2'd3 == M_AXIS_V_id_V_1_state)) | ((2'd1 == M_AXIS_V_id_V_1_state) & (1'b1 == M_AXIS_V_id_V_1_ack_out)) | ((2'd2 == M_AXIS_V_id_V_1_state) & (1'b1 == M_AXIS_V_id_V_1_vld_in)))) begin
            M_AXIS_V_id_V_1_state <= 2'd3;
        end else begin
            M_AXIS_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_keep_V_1_ack_out) & (1'b1 == M_AXIS_V_keep_V_1_vld_out))) begin
            M_AXIS_V_keep_V_1_sel_rd <= ~M_AXIS_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_keep_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_keep_V_1_ack_in) & (1'b1 == M_AXIS_V_keep_V_1_vld_in))) begin
            M_AXIS_V_keep_V_1_sel_wr <= ~M_AXIS_V_keep_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == M_AXIS_V_keep_V_1_state) & (1'b0 == M_AXIS_V_keep_V_1_vld_in)) | ((2'd3 == M_AXIS_V_keep_V_1_state) & (1'b0 == M_AXIS_V_keep_V_1_vld_in) & (1'b1 == M_AXIS_V_keep_V_1_ack_out)))) begin
            M_AXIS_V_keep_V_1_state <= 2'd2;
        end else if ((((2'd1 == M_AXIS_V_keep_V_1_state) & (1'b0 == M_AXIS_V_keep_V_1_ack_out)) | ((2'd3 == M_AXIS_V_keep_V_1_state) & (1'b0 == M_AXIS_V_keep_V_1_ack_out) & (1'b1 == M_AXIS_V_keep_V_1_vld_in)))) begin
            M_AXIS_V_keep_V_1_state <= 2'd1;
        end else if (((~((1'b0 == M_AXIS_V_keep_V_1_vld_in) & (1'b1 == M_AXIS_V_keep_V_1_ack_out)) & ~((1'b0 == M_AXIS_V_keep_V_1_ack_out) & (1'b1 == M_AXIS_V_keep_V_1_vld_in)) & (2'd3 == M_AXIS_V_keep_V_1_state)) | ((2'd1 == M_AXIS_V_keep_V_1_state) & (1'b1 == M_AXIS_V_keep_V_1_ack_out)) | ((2'd2 == M_AXIS_V_keep_V_1_state) & (1'b1 == M_AXIS_V_keep_V_1_vld_in)))) begin
            M_AXIS_V_keep_V_1_state <= 2'd3;
        end else begin
            M_AXIS_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_last_V_1_ack_out) & (1'b1 == M_AXIS_V_last_V_1_vld_out))) begin
            M_AXIS_V_last_V_1_sel_rd <= ~M_AXIS_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_last_V_1_ack_in) & (1'b1 == M_AXIS_V_last_V_1_vld_in))) begin
            M_AXIS_V_last_V_1_sel_wr <= ~M_AXIS_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == M_AXIS_V_last_V_1_state) & (1'b0 == M_AXIS_V_last_V_1_vld_in)) | ((2'd3 == M_AXIS_V_last_V_1_state) & (1'b0 == M_AXIS_V_last_V_1_vld_in) & (1'b1 == M_AXIS_V_last_V_1_ack_out)))) begin
            M_AXIS_V_last_V_1_state <= 2'd2;
        end else if ((((2'd1 == M_AXIS_V_last_V_1_state) & (1'b0 == M_AXIS_V_last_V_1_ack_out)) | ((2'd3 == M_AXIS_V_last_V_1_state) & (1'b0 == M_AXIS_V_last_V_1_ack_out) & (1'b1 == M_AXIS_V_last_V_1_vld_in)))) begin
            M_AXIS_V_last_V_1_state <= 2'd1;
        end else if (((~((1'b0 == M_AXIS_V_last_V_1_vld_in) & (1'b1 == M_AXIS_V_last_V_1_ack_out)) & ~((1'b0 == M_AXIS_V_last_V_1_ack_out) & (1'b1 == M_AXIS_V_last_V_1_vld_in)) & (2'd3 == M_AXIS_V_last_V_1_state)) | ((2'd1 == M_AXIS_V_last_V_1_state) & (1'b1 == M_AXIS_V_last_V_1_ack_out)) | ((2'd2 == M_AXIS_V_last_V_1_state) & (1'b1 == M_AXIS_V_last_V_1_vld_in)))) begin
            M_AXIS_V_last_V_1_state <= 2'd3;
        end else begin
            M_AXIS_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_strb_V_1_ack_out) & (1'b1 == M_AXIS_V_strb_V_1_vld_out))) begin
            M_AXIS_V_strb_V_1_sel_rd <= ~M_AXIS_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_strb_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_strb_V_1_ack_in) & (1'b1 == M_AXIS_V_strb_V_1_vld_in))) begin
            M_AXIS_V_strb_V_1_sel_wr <= ~M_AXIS_V_strb_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == M_AXIS_V_strb_V_1_state) & (1'b0 == M_AXIS_V_strb_V_1_vld_in)) | ((2'd3 == M_AXIS_V_strb_V_1_state) & (1'b0 == M_AXIS_V_strb_V_1_vld_in) & (1'b1 == M_AXIS_V_strb_V_1_ack_out)))) begin
            M_AXIS_V_strb_V_1_state <= 2'd2;
        end else if ((((2'd1 == M_AXIS_V_strb_V_1_state) & (1'b0 == M_AXIS_V_strb_V_1_ack_out)) | ((2'd3 == M_AXIS_V_strb_V_1_state) & (1'b0 == M_AXIS_V_strb_V_1_ack_out) & (1'b1 == M_AXIS_V_strb_V_1_vld_in)))) begin
            M_AXIS_V_strb_V_1_state <= 2'd1;
        end else if (((~((1'b0 == M_AXIS_V_strb_V_1_vld_in) & (1'b1 == M_AXIS_V_strb_V_1_ack_out)) & ~((1'b0 == M_AXIS_V_strb_V_1_ack_out) & (1'b1 == M_AXIS_V_strb_V_1_vld_in)) & (2'd3 == M_AXIS_V_strb_V_1_state)) | ((2'd1 == M_AXIS_V_strb_V_1_state) & (1'b1 == M_AXIS_V_strb_V_1_ack_out)) | ((2'd2 == M_AXIS_V_strb_V_1_state) & (1'b1 == M_AXIS_V_strb_V_1_vld_in)))) begin
            M_AXIS_V_strb_V_1_state <= 2'd3;
        end else begin
            M_AXIS_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_user_V_1_ack_out) & (1'b1 == M_AXIS_V_user_V_1_vld_out))) begin
            M_AXIS_V_user_V_1_sel_rd <= ~M_AXIS_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == M_AXIS_V_user_V_1_ack_in) & (1'b1 == M_AXIS_V_user_V_1_vld_in))) begin
            M_AXIS_V_user_V_1_sel_wr <= ~M_AXIS_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        M_AXIS_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((2'd2 == M_AXIS_V_user_V_1_state) & (1'b0 == M_AXIS_V_user_V_1_vld_in)) | ((2'd3 == M_AXIS_V_user_V_1_state) & (1'b0 == M_AXIS_V_user_V_1_vld_in) & (1'b1 == M_AXIS_V_user_V_1_ack_out)))) begin
            M_AXIS_V_user_V_1_state <= 2'd2;
        end else if ((((2'd1 == M_AXIS_V_user_V_1_state) & (1'b0 == M_AXIS_V_user_V_1_ack_out)) | ((2'd3 == M_AXIS_V_user_V_1_state) & (1'b0 == M_AXIS_V_user_V_1_ack_out) & (1'b1 == M_AXIS_V_user_V_1_vld_in)))) begin
            M_AXIS_V_user_V_1_state <= 2'd1;
        end else if (((~((1'b0 == M_AXIS_V_user_V_1_vld_in) & (1'b1 == M_AXIS_V_user_V_1_ack_out)) & ~((1'b0 == M_AXIS_V_user_V_1_ack_out) & (1'b1 == M_AXIS_V_user_V_1_vld_in)) & (2'd3 == M_AXIS_V_user_V_1_state)) | ((2'd1 == M_AXIS_V_user_V_1_state) & (1'b1 == M_AXIS_V_user_V_1_ack_out)) | ((2'd2 == M_AXIS_V_user_V_1_state) & (1'b1 == M_AXIS_V_user_V_1_vld_in)))) begin
            M_AXIS_V_user_V_1_state <= 2'd3;
        end else begin
            M_AXIS_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_data_V_0_ack_out) & (1'b1 == S_AXIS_V_data_V_0_vld_out))) begin
            S_AXIS_V_data_V_0_sel_rd <= ~S_AXIS_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_data_V_0_ack_in) & (1'b1 == S_AXIS_V_data_V_0_vld_in))) begin
            S_AXIS_V_data_V_0_sel_wr <= ~S_AXIS_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == S_AXIS_V_data_V_0_state) & (1'b0 == S_AXIS_V_data_V_0_vld_in)) | ((2'd3 == S_AXIS_V_data_V_0_state) & (1'b0 == S_AXIS_V_data_V_0_vld_in) & (1'b1 == S_AXIS_V_data_V_0_ack_out)))) begin
            S_AXIS_V_data_V_0_state <= 2'd2;
        end else if ((((2'd1 == S_AXIS_V_data_V_0_state) & (1'b0 == S_AXIS_V_data_V_0_ack_out)) | ((2'd3 == S_AXIS_V_data_V_0_state) & (1'b0 == S_AXIS_V_data_V_0_ack_out) & (1'b1 == S_AXIS_V_data_V_0_vld_in)))) begin
            S_AXIS_V_data_V_0_state <= 2'd1;
        end else if (((~((1'b0 == S_AXIS_V_data_V_0_vld_in) & (1'b1 == S_AXIS_V_data_V_0_ack_out)) & ~((1'b0 == S_AXIS_V_data_V_0_ack_out) & (1'b1 == S_AXIS_V_data_V_0_vld_in)) & (2'd3 == S_AXIS_V_data_V_0_state)) | ((2'd1 == S_AXIS_V_data_V_0_state) & (1'b1 == S_AXIS_V_data_V_0_ack_out)) | ((2'd2 == S_AXIS_V_data_V_0_state) & (1'b1 == S_AXIS_V_data_V_0_vld_in)))) begin
            S_AXIS_V_data_V_0_state <= 2'd3;
        end else begin
            S_AXIS_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_dest_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_dest_V_0_ack_out) & (1'b1 == S_AXIS_V_dest_V_0_vld_out))) begin
            S_AXIS_V_dest_V_0_sel_rd <= ~S_AXIS_V_dest_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_dest_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_dest_V_0_ack_in) & (1'b1 == S_AXIS_V_dest_V_0_vld_in))) begin
            S_AXIS_V_dest_V_0_sel_wr <= ~S_AXIS_V_dest_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == S_AXIS_V_dest_V_0_state) & (1'b0 == S_AXIS_V_dest_V_0_vld_in)) | ((2'd3 == S_AXIS_V_dest_V_0_state) & (1'b0 == S_AXIS_V_dest_V_0_vld_in) & (1'b1 == S_AXIS_V_dest_V_0_ack_out)))) begin
            S_AXIS_V_dest_V_0_state <= 2'd2;
        end else if ((((2'd1 == S_AXIS_V_dest_V_0_state) & (1'b0 == S_AXIS_V_dest_V_0_ack_out)) | ((2'd3 == S_AXIS_V_dest_V_0_state) & (1'b0 == S_AXIS_V_dest_V_0_ack_out) & (1'b1 == S_AXIS_V_dest_V_0_vld_in)))) begin
            S_AXIS_V_dest_V_0_state <= 2'd1;
        end else if (((~((1'b0 == S_AXIS_V_dest_V_0_vld_in) & (1'b1 == S_AXIS_V_dest_V_0_ack_out)) & ~((1'b0 == S_AXIS_V_dest_V_0_ack_out) & (1'b1 == S_AXIS_V_dest_V_0_vld_in)) & (2'd3 == S_AXIS_V_dest_V_0_state)) | ((2'd1 == S_AXIS_V_dest_V_0_state) & (1'b1 == S_AXIS_V_dest_V_0_ack_out)) | ((2'd2 == S_AXIS_V_dest_V_0_state) & (1'b1 == S_AXIS_V_dest_V_0_vld_in)))) begin
            S_AXIS_V_dest_V_0_state <= 2'd3;
        end else begin
            S_AXIS_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_id_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_id_V_0_ack_out) & (1'b1 == S_AXIS_V_id_V_0_vld_out))) begin
            S_AXIS_V_id_V_0_sel_rd <= ~S_AXIS_V_id_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_id_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_id_V_0_ack_in) & (1'b1 == S_AXIS_V_id_V_0_vld_in))) begin
            S_AXIS_V_id_V_0_sel_wr <= ~S_AXIS_V_id_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_id_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == S_AXIS_V_id_V_0_state) & (1'b0 == S_AXIS_V_id_V_0_vld_in)) | ((2'd3 == S_AXIS_V_id_V_0_state) & (1'b0 == S_AXIS_V_id_V_0_vld_in) & (1'b1 == S_AXIS_V_id_V_0_ack_out)))) begin
            S_AXIS_V_id_V_0_state <= 2'd2;
        end else if ((((2'd1 == S_AXIS_V_id_V_0_state) & (1'b0 == S_AXIS_V_id_V_0_ack_out)) | ((2'd3 == S_AXIS_V_id_V_0_state) & (1'b0 == S_AXIS_V_id_V_0_ack_out) & (1'b1 == S_AXIS_V_id_V_0_vld_in)))) begin
            S_AXIS_V_id_V_0_state <= 2'd1;
        end else if (((~((1'b0 == S_AXIS_V_id_V_0_vld_in) & (1'b1 == S_AXIS_V_id_V_0_ack_out)) & ~((1'b0 == S_AXIS_V_id_V_0_ack_out) & (1'b1 == S_AXIS_V_id_V_0_vld_in)) & (2'd3 == S_AXIS_V_id_V_0_state)) | ((2'd1 == S_AXIS_V_id_V_0_state) & (1'b1 == S_AXIS_V_id_V_0_ack_out)) | ((2'd2 == S_AXIS_V_id_V_0_state) & (1'b1 == S_AXIS_V_id_V_0_vld_in)))) begin
            S_AXIS_V_id_V_0_state <= 2'd3;
        end else begin
            S_AXIS_V_id_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_keep_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_keep_V_0_ack_out) & (1'b1 == S_AXIS_V_keep_V_0_vld_out))) begin
            S_AXIS_V_keep_V_0_sel_rd <= ~S_AXIS_V_keep_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_keep_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_keep_V_0_ack_in) & (1'b1 == S_AXIS_V_keep_V_0_vld_in))) begin
            S_AXIS_V_keep_V_0_sel_wr <= ~S_AXIS_V_keep_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_keep_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == S_AXIS_V_keep_V_0_state) & (1'b0 == S_AXIS_V_keep_V_0_vld_in)) | ((2'd3 == S_AXIS_V_keep_V_0_state) & (1'b0 == S_AXIS_V_keep_V_0_vld_in) & (1'b1 == S_AXIS_V_keep_V_0_ack_out)))) begin
            S_AXIS_V_keep_V_0_state <= 2'd2;
        end else if ((((2'd1 == S_AXIS_V_keep_V_0_state) & (1'b0 == S_AXIS_V_keep_V_0_ack_out)) | ((2'd3 == S_AXIS_V_keep_V_0_state) & (1'b0 == S_AXIS_V_keep_V_0_ack_out) & (1'b1 == S_AXIS_V_keep_V_0_vld_in)))) begin
            S_AXIS_V_keep_V_0_state <= 2'd1;
        end else if (((~((1'b0 == S_AXIS_V_keep_V_0_vld_in) & (1'b1 == S_AXIS_V_keep_V_0_ack_out)) & ~((1'b0 == S_AXIS_V_keep_V_0_ack_out) & (1'b1 == S_AXIS_V_keep_V_0_vld_in)) & (2'd3 == S_AXIS_V_keep_V_0_state)) | ((2'd1 == S_AXIS_V_keep_V_0_state) & (1'b1 == S_AXIS_V_keep_V_0_ack_out)) | ((2'd2 == S_AXIS_V_keep_V_0_state) & (1'b1 == S_AXIS_V_keep_V_0_vld_in)))) begin
            S_AXIS_V_keep_V_0_state <= 2'd3;
        end else begin
            S_AXIS_V_keep_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_strb_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_strb_V_0_ack_out) & (1'b1 == S_AXIS_V_strb_V_0_vld_out))) begin
            S_AXIS_V_strb_V_0_sel_rd <= ~S_AXIS_V_strb_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_strb_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_strb_V_0_ack_in) & (1'b1 == S_AXIS_V_strb_V_0_vld_in))) begin
            S_AXIS_V_strb_V_0_sel_wr <= ~S_AXIS_V_strb_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_strb_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == S_AXIS_V_strb_V_0_state) & (1'b0 == S_AXIS_V_strb_V_0_vld_in)) | ((2'd3 == S_AXIS_V_strb_V_0_state) & (1'b0 == S_AXIS_V_strb_V_0_vld_in) & (1'b1 == S_AXIS_V_strb_V_0_ack_out)))) begin
            S_AXIS_V_strb_V_0_state <= 2'd2;
        end else if ((((2'd1 == S_AXIS_V_strb_V_0_state) & (1'b0 == S_AXIS_V_strb_V_0_ack_out)) | ((2'd3 == S_AXIS_V_strb_V_0_state) & (1'b0 == S_AXIS_V_strb_V_0_ack_out) & (1'b1 == S_AXIS_V_strb_V_0_vld_in)))) begin
            S_AXIS_V_strb_V_0_state <= 2'd1;
        end else if (((~((1'b0 == S_AXIS_V_strb_V_0_vld_in) & (1'b1 == S_AXIS_V_strb_V_0_ack_out)) & ~((1'b0 == S_AXIS_V_strb_V_0_ack_out) & (1'b1 == S_AXIS_V_strb_V_0_vld_in)) & (2'd3 == S_AXIS_V_strb_V_0_state)) | ((2'd1 == S_AXIS_V_strb_V_0_state) & (1'b1 == S_AXIS_V_strb_V_0_ack_out)) | ((2'd2 == S_AXIS_V_strb_V_0_state) & (1'b1 == S_AXIS_V_strb_V_0_vld_in)))) begin
            S_AXIS_V_strb_V_0_state <= 2'd3;
        end else begin
            S_AXIS_V_strb_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_user_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_user_V_0_ack_out) & (1'b1 == S_AXIS_V_user_V_0_vld_out))) begin
            S_AXIS_V_user_V_0_sel_rd <= ~S_AXIS_V_user_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_user_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == S_AXIS_V_user_V_0_ack_in) & (1'b1 == S_AXIS_V_user_V_0_vld_in))) begin
            S_AXIS_V_user_V_0_sel_wr <= ~S_AXIS_V_user_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        S_AXIS_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == S_AXIS_V_user_V_0_state) & (1'b0 == S_AXIS_V_user_V_0_vld_in)) | ((2'd3 == S_AXIS_V_user_V_0_state) & (1'b0 == S_AXIS_V_user_V_0_vld_in) & (1'b1 == S_AXIS_V_user_V_0_ack_out)))) begin
            S_AXIS_V_user_V_0_state <= 2'd2;
        end else if ((((2'd1 == S_AXIS_V_user_V_0_state) & (1'b0 == S_AXIS_V_user_V_0_ack_out)) | ((2'd3 == S_AXIS_V_user_V_0_state) & (1'b0 == S_AXIS_V_user_V_0_ack_out) & (1'b1 == S_AXIS_V_user_V_0_vld_in)))) begin
            S_AXIS_V_user_V_0_state <= 2'd1;
        end else if (((~((1'b0 == S_AXIS_V_user_V_0_vld_in) & (1'b1 == S_AXIS_V_user_V_0_ack_out)) & ~((1'b0 == S_AXIS_V_user_V_0_ack_out) & (1'b1 == S_AXIS_V_user_V_0_vld_in)) & (2'd3 == S_AXIS_V_user_V_0_state)) | ((2'd1 == S_AXIS_V_user_V_0_state) & (1'b1 == S_AXIS_V_user_V_0_ack_out)) | ((2'd2 == S_AXIS_V_user_V_0_state) & (1'b1 == S_AXIS_V_user_V_0_vld_in)))) begin
            S_AXIS_V_user_V_0_state <= 2'd3;
        end else begin
            S_AXIS_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_count_occ_v2_fu_366_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_count_occ_v2_fu_366_ap_start_reg <= 1'b1;
        end else if ((grp_count_occ_v2_fu_366_ap_ready == 1'b1)) begin
            grp_count_occ_v2_fu_366_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sort_occ_v2_fu_375_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12))) begin
            grp_sort_occ_v2_fu_375_ap_start_reg <= 1'b1;
        end else if ((grp_sort_occ_v2_fu_375_ap_ready == 1'b1)) begin
            grp_sort_occ_v2_fu_375_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state22))) begin
        i_1_reg_355 <= i_5_reg_669;
    end else if (((1'b1 == ap_CS_fsm_state19) & (grp_sort_occ_v2_fu_375_ap_done == 1'b1))) begin
        i_1_reg_355 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        i_reg_288 <= i_4_reg_629;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_288 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_16_fu_482_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        invdar2_i_reg_311 <= 8'd0;
    end else if (((tmp_2_i_fu_499_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        invdar2_i_reg_311 <= indvarinc3_i_fu_488_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_i_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        invdar5_i_reg_322 <= 8'd0;
    end else if (((tmp_4_i_fu_516_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        invdar5_i_reg_322 <= indvarinc6_i_fu_505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_4_i_fu_516_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        invdar8_i_reg_333 <= 8'd0;
    end else if (((tmp_6_i_fu_533_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        invdar8_i_reg_333 <= indvarinc9_i_fu_522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_404_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        invdar_i_reg_300 <= 8'd0;
    end else if (((tmp_i_16_fu_482_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        invdar_i_reg_300 <= indvarinc_i_fu_471_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_398_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        invdar_reg_277 <= indvarinc_fu_387_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        invdar_reg_277 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state22))) begin
        val_4_reg_344 <= tmp_last_V_reg_679;
    end else if (((1'b1 == ap_CS_fsm_state19) & (grp_sort_occ_v2_fu_375_ap_done == 1'b1))) begin
        val_4_reg_344 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_data_V_1_load_A)) begin
        M_AXIS_V_data_V_1_payload_A <= tab_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_data_V_1_load_B)) begin
        M_AXIS_V_data_V_1_payload_B <= tab_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_dest_V_1_load_A)) begin
        M_AXIS_V_dest_V_1_payload_A <= tmp_dest_V_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_dest_V_1_load_B)) begin
        M_AXIS_V_dest_V_1_payload_B <= tmp_dest_V_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_id_V_1_load_A)) begin
        M_AXIS_V_id_V_1_payload_A <= tmp_id_V_fu_146;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_id_V_1_load_B)) begin
        M_AXIS_V_id_V_1_payload_B <= tmp_id_V_fu_146;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_keep_V_1_load_A)) begin
        M_AXIS_V_keep_V_1_payload_A <= tmp_keep_V_fu_134;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_keep_V_1_load_B)) begin
        M_AXIS_V_keep_V_1_payload_B <= tmp_keep_V_fu_134;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_last_V_1_load_A)) begin
        M_AXIS_V_last_V_1_payload_A <= tmp_last_V_reg_679;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_last_V_1_load_B)) begin
        M_AXIS_V_last_V_1_payload_B <= tmp_last_V_reg_679;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_strb_V_1_load_A)) begin
        M_AXIS_V_strb_V_1_payload_A <= tmp_strb_V_fu_138;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_strb_V_1_load_B)) begin
        M_AXIS_V_strb_V_1_payload_B <= tmp_strb_V_fu_138;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_user_V_1_load_A)) begin
        M_AXIS_V_user_V_1_payload_A <= tmp_user_V_fu_142;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == M_AXIS_V_user_V_1_load_B)) begin
        M_AXIS_V_user_V_1_payload_B <= tmp_user_V_fu_142;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_data_V_0_load_A)) begin
        S_AXIS_V_data_V_0_payload_A <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_data_V_0_load_B)) begin
        S_AXIS_V_data_V_0_payload_B <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_dest_V_0_load_A)) begin
        S_AXIS_V_dest_V_0_payload_A <= S_AXIS_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_dest_V_0_load_B)) begin
        S_AXIS_V_dest_V_0_payload_B <= S_AXIS_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_id_V_0_load_A)) begin
        S_AXIS_V_id_V_0_payload_A <= S_AXIS_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_id_V_0_load_B)) begin
        S_AXIS_V_id_V_0_payload_B <= S_AXIS_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_keep_V_0_load_A)) begin
        S_AXIS_V_keep_V_0_payload_A <= S_AXIS_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_keep_V_0_load_B)) begin
        S_AXIS_V_keep_V_0_payload_B <= S_AXIS_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_strb_V_0_load_A)) begin
        S_AXIS_V_strb_V_0_payload_A <= S_AXIS_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_strb_V_0_load_B)) begin
        S_AXIS_V_strb_V_0_payload_B <= S_AXIS_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_user_V_0_load_A)) begin
        S_AXIS_V_user_V_0_payload_A <= S_AXIS_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == S_AXIS_V_user_V_0_load_B)) begin
        S_AXIS_V_user_V_0_payload_B <= S_AXIS_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_4_reg_629 <= i_4_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        i_5_reg_669 <= i_5_fu_545_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_dest_V_fu_150 <= S_AXIS_V_dest_V_0_data_out;
        tmp_id_V_fu_146 <= S_AXIS_V_id_V_0_data_out;
        tmp_keep_V_fu_134 <= S_AXIS_V_keep_V_0_data_out;
        tmp_strb_V_fu_138 <= S_AXIS_V_strb_V_0_data_out;
        tmp_user_V_fu_142 <= S_AXIS_V_user_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_539_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        tmp_last_V_reg_679 <= tmp_last_V_fu_562_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_TDATA_blk_n = M_AXIS_V_data_V_1_state[1'd1];
    end else begin
        M_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == M_AXIS_V_data_V_1_sel)) begin
        M_AXIS_V_data_V_1_data_out = M_AXIS_V_data_V_1_payload_B;
    end else begin
        M_AXIS_V_data_V_1_data_out = M_AXIS_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_V_data_V_1_vld_in = 1'b1;
    end else begin
        M_AXIS_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == M_AXIS_V_dest_V_1_sel)) begin
        M_AXIS_V_dest_V_1_data_out = M_AXIS_V_dest_V_1_payload_B;
    end else begin
        M_AXIS_V_dest_V_1_data_out = M_AXIS_V_dest_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_V_dest_V_1_vld_in = 1'b1;
    end else begin
        M_AXIS_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == M_AXIS_V_id_V_1_sel)) begin
        M_AXIS_V_id_V_1_data_out = M_AXIS_V_id_V_1_payload_B;
    end else begin
        M_AXIS_V_id_V_1_data_out = M_AXIS_V_id_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_V_id_V_1_vld_in = 1'b1;
    end else begin
        M_AXIS_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == M_AXIS_V_keep_V_1_sel)) begin
        M_AXIS_V_keep_V_1_data_out = M_AXIS_V_keep_V_1_payload_B;
    end else begin
        M_AXIS_V_keep_V_1_data_out = M_AXIS_V_keep_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_V_keep_V_1_vld_in = 1'b1;
    end else begin
        M_AXIS_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == M_AXIS_V_last_V_1_sel)) begin
        M_AXIS_V_last_V_1_data_out = M_AXIS_V_last_V_1_payload_B;
    end else begin
        M_AXIS_V_last_V_1_data_out = M_AXIS_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_V_last_V_1_vld_in = 1'b1;
    end else begin
        M_AXIS_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == M_AXIS_V_strb_V_1_sel)) begin
        M_AXIS_V_strb_V_1_data_out = M_AXIS_V_strb_V_1_payload_B;
    end else begin
        M_AXIS_V_strb_V_1_data_out = M_AXIS_V_strb_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_V_strb_V_1_vld_in = 1'b1;
    end else begin
        M_AXIS_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == M_AXIS_V_user_V_1_sel)) begin
        M_AXIS_V_user_V_1_data_out = M_AXIS_V_user_V_1_payload_B;
    end else begin
        M_AXIS_V_user_V_1_data_out = M_AXIS_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
        M_AXIS_V_user_V_1_vld_in = 1'b1;
    end else begin
        M_AXIS_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        S_AXIS_TDATA_blk_n = S_AXIS_V_data_V_0_state[1'd0];
    end else begin
        S_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        S_AXIS_V_data_V_0_ack_out = 1'b1;
    end else begin
        S_AXIS_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == S_AXIS_V_data_V_0_sel)) begin
        S_AXIS_V_data_V_0_data_out = S_AXIS_V_data_V_0_payload_B;
    end else begin
        S_AXIS_V_data_V_0_data_out = S_AXIS_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        S_AXIS_V_dest_V_0_ack_out = 1'b1;
    end else begin
        S_AXIS_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == S_AXIS_V_dest_V_0_sel)) begin
        S_AXIS_V_dest_V_0_data_out = S_AXIS_V_dest_V_0_payload_B;
    end else begin
        S_AXIS_V_dest_V_0_data_out = S_AXIS_V_dest_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        S_AXIS_V_id_V_0_ack_out = 1'b1;
    end else begin
        S_AXIS_V_id_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == S_AXIS_V_id_V_0_sel)) begin
        S_AXIS_V_id_V_0_data_out = S_AXIS_V_id_V_0_payload_B;
    end else begin
        S_AXIS_V_id_V_0_data_out = S_AXIS_V_id_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        S_AXIS_V_keep_V_0_ack_out = 1'b1;
    end else begin
        S_AXIS_V_keep_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == S_AXIS_V_keep_V_0_sel)) begin
        S_AXIS_V_keep_V_0_data_out = S_AXIS_V_keep_V_0_payload_B;
    end else begin
        S_AXIS_V_keep_V_0_data_out = S_AXIS_V_keep_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        S_AXIS_V_strb_V_0_ack_out = 1'b1;
    end else begin
        S_AXIS_V_strb_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == S_AXIS_V_strb_V_0_sel)) begin
        S_AXIS_V_strb_V_0_data_out = S_AXIS_V_strb_V_0_payload_B;
    end else begin
        S_AXIS_V_strb_V_0_data_out = S_AXIS_V_strb_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        S_AXIS_V_user_V_0_ack_out = 1'b1;
    end else begin
        S_AXIS_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == S_AXIS_V_user_V_0_sel)) begin
        S_AXIS_V_user_V_0_data_out = S_AXIS_V_user_V_0_payload_B;
    end else begin
        S_AXIS_V_user_V_0_data_out = S_AXIS_V_user_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        array2_address0 = grp_sort_occ_v2_fu_375_array_dst_address0;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19))) begin
        array2_address0 = grp_sort_occ_v2_fu_375_array_src_address0;
    end else begin
        array2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        array2_ce0 = grp_sort_occ_v2_fu_375_array_dst_ce0;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19))) begin
        array2_ce0 = grp_sort_occ_v2_fu_375_array_src_ce0;
    end else begin
        array2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        array2_we0 = grp_sort_occ_v2_fu_375_array_dst_we0;
    end else begin
        array2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        count_1_address0 = tmp_i_fu_477_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        count_1_address0 = grp_sort_occ_v2_fu_375_count_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_1_address0 = grp_count_occ_v2_fu_366_c1_address0;
    end else begin
        count_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        count_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        count_1_ce0 = grp_sort_occ_v2_fu_375_count_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_1_ce0 = grp_count_occ_v2_fu_366_c1_ce0;
    end else begin
        count_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_1_ce1 = grp_count_occ_v2_fu_366_c1_ce1;
    end else begin
        count_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        count_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        count_1_d0 = grp_sort_occ_v2_fu_375_count_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_1_d0 = grp_count_occ_v2_fu_366_c1_d0;
    end else begin
        count_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        count_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        count_1_we0 = grp_sort_occ_v2_fu_375_count_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_1_we0 = grp_count_occ_v2_fu_366_c1_we0;
    end else begin
        count_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_1_we1 = grp_count_occ_v2_fu_366_c1_we1;
    end else begin
        count_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        count_2_address0 = tmp_1_i_fu_494_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        count_2_address0 = grp_sort_occ_v2_fu_375_count_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_2_address0 = grp_count_occ_v2_fu_366_c2_address0;
    end else begin
        count_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        count_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        count_2_ce0 = grp_sort_occ_v2_fu_375_count_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_2_ce0 = grp_count_occ_v2_fu_366_c2_ce0;
    end else begin
        count_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_2_ce1 = grp_count_occ_v2_fu_366_c2_ce1;
    end else begin
        count_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        count_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        count_2_d0 = grp_sort_occ_v2_fu_375_count_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_2_d0 = grp_count_occ_v2_fu_366_c2_d0;
    end else begin
        count_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        count_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        count_2_we0 = grp_sort_occ_v2_fu_375_count_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_2_we0 = grp_count_occ_v2_fu_366_c2_we0;
    end else begin
        count_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_2_we1 = grp_count_occ_v2_fu_366_c2_we1;
    end else begin
        count_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        count_3_address0 = tmp_3_i_fu_511_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        count_3_address0 = grp_sort_occ_v2_fu_375_count_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_3_address0 = grp_count_occ_v2_fu_366_c3_address0;
    end else begin
        count_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        count_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        count_3_ce0 = grp_sort_occ_v2_fu_375_count_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_3_ce0 = grp_count_occ_v2_fu_366_c3_ce0;
    end else begin
        count_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_3_ce1 = grp_count_occ_v2_fu_366_c3_ce1;
    end else begin
        count_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        count_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        count_3_d0 = grp_sort_occ_v2_fu_375_count_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_3_d0 = grp_count_occ_v2_fu_366_c3_d0;
    end else begin
        count_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        count_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        count_3_we0 = grp_sort_occ_v2_fu_375_count_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_3_we0 = grp_count_occ_v2_fu_366_c3_we0;
    end else begin
        count_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_3_we1 = grp_count_occ_v2_fu_366_c3_we1;
    end else begin
        count_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        count_4_address0 = tmp_5_i_fu_528_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        count_4_address0 = grp_sort_occ_v2_fu_375_count_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_4_address0 = grp_count_occ_v2_fu_366_c4_address0;
    end else begin
        count_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        count_4_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        count_4_ce0 = grp_sort_occ_v2_fu_375_count_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_4_ce0 = grp_count_occ_v2_fu_366_c4_ce0;
    end else begin
        count_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_4_ce1 = grp_count_occ_v2_fu_366_c4_ce1;
    end else begin
        count_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        count_4_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        count_4_d0 = grp_sort_occ_v2_fu_375_count_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_4_d0 = grp_count_occ_v2_fu_366_c4_d0;
    end else begin
        count_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        count_4_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        count_4_we0 = grp_sort_occ_v2_fu_375_count_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        count_4_we0 = grp_count_occ_v2_fu_366_c4_we0;
    end else begin
        count_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        count_4_we1 = grp_count_occ_v2_fu_366_c4_we1;
    end else begin
        count_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19))) begin
        grp_sort_occ_v2_fu_375_array_src_q0 = array2_q0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        grp_sort_occ_v2_fu_375_array_src_q0 = tab_q0;
    end else begin
        grp_sort_occ_v2_fu_375_array_src_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_sort_occ_v2_fu_375_count_q0 = count_4_q0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_sort_occ_v2_fu_375_count_q0 = count_3_q0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_sort_occ_v2_fu_375_count_q0 = count_2_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_sort_occ_v2_fu_375_count_q0 = count_1_q0;
    end else begin
        grp_sort_occ_v2_fu_375_count_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_sort_occ_v2_fu_375_shift = 6'd24;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_sort_occ_v2_fu_375_shift = 6'd16;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_sort_occ_v2_fu_375_shift = 6'd8;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_sort_occ_v2_fu_375_shift = 6'd0;
    end else begin
        grp_sort_occ_v2_fu_375_shift = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tab_address0 = tmp_17_fu_551_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tab_address0 = tmp_16_fu_441_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tab_address0 = tmp_fu_393_p1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19))) begin
        tab_address0 = grp_sort_occ_v2_fu_375_array_dst_address0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        tab_address0 = grp_sort_occ_v2_fu_375_array_src_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tab_address0 = grp_count_occ_v2_fu_366_array_src_address0;
    end else begin
        tab_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5)))) begin
        tab_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19))) begin
        tab_ce0 = grp_sort_occ_v2_fu_375_array_dst_ce0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        tab_ce0 = grp_sort_occ_v2_fu_375_array_src_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tab_ce0 = grp_count_occ_v2_fu_366_array_src_ce0;
    end else begin
        tab_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tab_d0 = S_AXIS_V_data_V_0_data_out;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tab_d0 = 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19))) begin
        tab_d0 = grp_sort_occ_v2_fu_375_array_dst_d0;
    end else begin
        tab_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5)))) begin
        tab_we0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19))) begin
        tab_we0 = grp_sort_occ_v2_fu_375_array_dst_we0;
    end else begin
        tab_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_s_fu_398_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond1_fu_404_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == S_AXIS_V_data_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((tmp_i_16_fu_482_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((tmp_2_i_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((tmp_4_i_fu_516_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((tmp_6_i_fu_533_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_count_occ_v2_fu_366_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_sort_occ_v2_fu_375_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_sort_occ_v2_fu_375_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (grp_sort_occ_v2_fu_375_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (grp_sort_occ_v2_fu_375_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((exitcond_fu_539_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == M_AXIS_V_data_V_1_ack_in) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TDATA = M_AXIS_V_data_V_1_data_out;

assign M_AXIS_TDEST = M_AXIS_V_dest_V_1_data_out;

assign M_AXIS_TID = M_AXIS_V_id_V_1_data_out;

assign M_AXIS_TKEEP = M_AXIS_V_keep_V_1_data_out;

assign M_AXIS_TLAST = M_AXIS_V_last_V_1_data_out;

assign M_AXIS_TSTRB = M_AXIS_V_strb_V_1_data_out;

assign M_AXIS_TUSER = M_AXIS_V_user_V_1_data_out;

assign M_AXIS_TVALID = M_AXIS_V_dest_V_1_state[1'd0];

assign M_AXIS_V_data_V_1_ack_in = M_AXIS_V_data_V_1_state[1'd1];

assign M_AXIS_V_data_V_1_ack_out = M_AXIS_TREADY;

assign M_AXIS_V_data_V_1_load_A = (~M_AXIS_V_data_V_1_sel_wr & M_AXIS_V_data_V_1_state_cmp_full);

assign M_AXIS_V_data_V_1_load_B = (M_AXIS_V_data_V_1_state_cmp_full & M_AXIS_V_data_V_1_sel_wr);

assign M_AXIS_V_data_V_1_sel = M_AXIS_V_data_V_1_sel_rd;

assign M_AXIS_V_data_V_1_state_cmp_full = ((M_AXIS_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign M_AXIS_V_data_V_1_vld_out = M_AXIS_V_data_V_1_state[1'd0];

assign M_AXIS_V_dest_V_1_ack_in = M_AXIS_V_dest_V_1_state[1'd1];

assign M_AXIS_V_dest_V_1_ack_out = M_AXIS_TREADY;

assign M_AXIS_V_dest_V_1_load_A = (~M_AXIS_V_dest_V_1_sel_wr & M_AXIS_V_dest_V_1_state_cmp_full);

assign M_AXIS_V_dest_V_1_load_B = (M_AXIS_V_dest_V_1_state_cmp_full & M_AXIS_V_dest_V_1_sel_wr);

assign M_AXIS_V_dest_V_1_sel = M_AXIS_V_dest_V_1_sel_rd;

assign M_AXIS_V_dest_V_1_state_cmp_full = ((M_AXIS_V_dest_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign M_AXIS_V_dest_V_1_vld_out = M_AXIS_V_dest_V_1_state[1'd0];

assign M_AXIS_V_id_V_1_ack_in = M_AXIS_V_id_V_1_state[1'd1];

assign M_AXIS_V_id_V_1_ack_out = M_AXIS_TREADY;

assign M_AXIS_V_id_V_1_load_A = (~M_AXIS_V_id_V_1_sel_wr & M_AXIS_V_id_V_1_state_cmp_full);

assign M_AXIS_V_id_V_1_load_B = (M_AXIS_V_id_V_1_state_cmp_full & M_AXIS_V_id_V_1_sel_wr);

assign M_AXIS_V_id_V_1_sel = M_AXIS_V_id_V_1_sel_rd;

assign M_AXIS_V_id_V_1_state_cmp_full = ((M_AXIS_V_id_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign M_AXIS_V_id_V_1_vld_out = M_AXIS_V_id_V_1_state[1'd0];

assign M_AXIS_V_keep_V_1_ack_in = M_AXIS_V_keep_V_1_state[1'd1];

assign M_AXIS_V_keep_V_1_ack_out = M_AXIS_TREADY;

assign M_AXIS_V_keep_V_1_load_A = (~M_AXIS_V_keep_V_1_sel_wr & M_AXIS_V_keep_V_1_state_cmp_full);

assign M_AXIS_V_keep_V_1_load_B = (M_AXIS_V_keep_V_1_state_cmp_full & M_AXIS_V_keep_V_1_sel_wr);

assign M_AXIS_V_keep_V_1_sel = M_AXIS_V_keep_V_1_sel_rd;

assign M_AXIS_V_keep_V_1_state_cmp_full = ((M_AXIS_V_keep_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign M_AXIS_V_keep_V_1_vld_out = M_AXIS_V_keep_V_1_state[1'd0];

assign M_AXIS_V_last_V_1_ack_in = M_AXIS_V_last_V_1_state[1'd1];

assign M_AXIS_V_last_V_1_ack_out = M_AXIS_TREADY;

assign M_AXIS_V_last_V_1_load_A = (~M_AXIS_V_last_V_1_sel_wr & M_AXIS_V_last_V_1_state_cmp_full);

assign M_AXIS_V_last_V_1_load_B = (M_AXIS_V_last_V_1_state_cmp_full & M_AXIS_V_last_V_1_sel_wr);

assign M_AXIS_V_last_V_1_sel = M_AXIS_V_last_V_1_sel_rd;

assign M_AXIS_V_last_V_1_state_cmp_full = ((M_AXIS_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign M_AXIS_V_last_V_1_vld_out = M_AXIS_V_last_V_1_state[1'd0];

assign M_AXIS_V_strb_V_1_ack_in = M_AXIS_V_strb_V_1_state[1'd1];

assign M_AXIS_V_strb_V_1_ack_out = M_AXIS_TREADY;

assign M_AXIS_V_strb_V_1_load_A = (~M_AXIS_V_strb_V_1_sel_wr & M_AXIS_V_strb_V_1_state_cmp_full);

assign M_AXIS_V_strb_V_1_load_B = (M_AXIS_V_strb_V_1_state_cmp_full & M_AXIS_V_strb_V_1_sel_wr);

assign M_AXIS_V_strb_V_1_sel = M_AXIS_V_strb_V_1_sel_rd;

assign M_AXIS_V_strb_V_1_state_cmp_full = ((M_AXIS_V_strb_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign M_AXIS_V_strb_V_1_vld_out = M_AXIS_V_strb_V_1_state[1'd0];

assign M_AXIS_V_user_V_1_ack_in = M_AXIS_V_user_V_1_state[1'd1];

assign M_AXIS_V_user_V_1_ack_out = M_AXIS_TREADY;

assign M_AXIS_V_user_V_1_load_A = (~M_AXIS_V_user_V_1_sel_wr & M_AXIS_V_user_V_1_state_cmp_full);

assign M_AXIS_V_user_V_1_load_B = (M_AXIS_V_user_V_1_state_cmp_full & M_AXIS_V_user_V_1_sel_wr);

assign M_AXIS_V_user_V_1_sel = M_AXIS_V_user_V_1_sel_rd;

assign M_AXIS_V_user_V_1_state_cmp_full = ((M_AXIS_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign M_AXIS_V_user_V_1_vld_out = M_AXIS_V_user_V_1_state[1'd0];

assign S_AXIS_TREADY = S_AXIS_V_dest_V_0_state[1'd1];

assign S_AXIS_V_data_V_0_ack_in = S_AXIS_V_data_V_0_state[1'd1];

assign S_AXIS_V_data_V_0_load_A = (~S_AXIS_V_data_V_0_sel_wr & S_AXIS_V_data_V_0_state_cmp_full);

assign S_AXIS_V_data_V_0_load_B = (S_AXIS_V_data_V_0_state_cmp_full & S_AXIS_V_data_V_0_sel_wr);

assign S_AXIS_V_data_V_0_sel = S_AXIS_V_data_V_0_sel_rd;

assign S_AXIS_V_data_V_0_state_cmp_full = ((S_AXIS_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign S_AXIS_V_data_V_0_vld_in = S_AXIS_TVALID;

assign S_AXIS_V_data_V_0_vld_out = S_AXIS_V_data_V_0_state[1'd0];

assign S_AXIS_V_dest_V_0_ack_in = S_AXIS_V_dest_V_0_state[1'd1];

assign S_AXIS_V_dest_V_0_load_A = (~S_AXIS_V_dest_V_0_sel_wr & S_AXIS_V_dest_V_0_state_cmp_full);

assign S_AXIS_V_dest_V_0_load_B = (S_AXIS_V_dest_V_0_state_cmp_full & S_AXIS_V_dest_V_0_sel_wr);

assign S_AXIS_V_dest_V_0_sel = S_AXIS_V_dest_V_0_sel_rd;

assign S_AXIS_V_dest_V_0_state_cmp_full = ((S_AXIS_V_dest_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign S_AXIS_V_dest_V_0_vld_in = S_AXIS_TVALID;

assign S_AXIS_V_dest_V_0_vld_out = S_AXIS_V_dest_V_0_state[1'd0];

assign S_AXIS_V_id_V_0_ack_in = S_AXIS_V_id_V_0_state[1'd1];

assign S_AXIS_V_id_V_0_load_A = (~S_AXIS_V_id_V_0_sel_wr & S_AXIS_V_id_V_0_state_cmp_full);

assign S_AXIS_V_id_V_0_load_B = (S_AXIS_V_id_V_0_state_cmp_full & S_AXIS_V_id_V_0_sel_wr);

assign S_AXIS_V_id_V_0_sel = S_AXIS_V_id_V_0_sel_rd;

assign S_AXIS_V_id_V_0_state_cmp_full = ((S_AXIS_V_id_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign S_AXIS_V_id_V_0_vld_in = S_AXIS_TVALID;

assign S_AXIS_V_id_V_0_vld_out = S_AXIS_V_id_V_0_state[1'd0];

assign S_AXIS_V_keep_V_0_ack_in = S_AXIS_V_keep_V_0_state[1'd1];

assign S_AXIS_V_keep_V_0_load_A = (~S_AXIS_V_keep_V_0_sel_wr & S_AXIS_V_keep_V_0_state_cmp_full);

assign S_AXIS_V_keep_V_0_load_B = (S_AXIS_V_keep_V_0_state_cmp_full & S_AXIS_V_keep_V_0_sel_wr);

assign S_AXIS_V_keep_V_0_sel = S_AXIS_V_keep_V_0_sel_rd;

assign S_AXIS_V_keep_V_0_state_cmp_full = ((S_AXIS_V_keep_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign S_AXIS_V_keep_V_0_vld_in = S_AXIS_TVALID;

assign S_AXIS_V_keep_V_0_vld_out = S_AXIS_V_keep_V_0_state[1'd0];

assign S_AXIS_V_strb_V_0_ack_in = S_AXIS_V_strb_V_0_state[1'd1];

assign S_AXIS_V_strb_V_0_load_A = (~S_AXIS_V_strb_V_0_sel_wr & S_AXIS_V_strb_V_0_state_cmp_full);

assign S_AXIS_V_strb_V_0_load_B = (S_AXIS_V_strb_V_0_state_cmp_full & S_AXIS_V_strb_V_0_sel_wr);

assign S_AXIS_V_strb_V_0_sel = S_AXIS_V_strb_V_0_sel_rd;

assign S_AXIS_V_strb_V_0_state_cmp_full = ((S_AXIS_V_strb_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign S_AXIS_V_strb_V_0_vld_in = S_AXIS_TVALID;

assign S_AXIS_V_strb_V_0_vld_out = S_AXIS_V_strb_V_0_state[1'd0];

assign S_AXIS_V_user_V_0_ack_in = S_AXIS_V_user_V_0_state[1'd1];

assign S_AXIS_V_user_V_0_load_A = (~S_AXIS_V_user_V_0_sel_wr & S_AXIS_V_user_V_0_state_cmp_full);

assign S_AXIS_V_user_V_0_load_B = (S_AXIS_V_user_V_0_state_cmp_full & S_AXIS_V_user_V_0_sel_wr);

assign S_AXIS_V_user_V_0_sel = S_AXIS_V_user_V_0_sel_rd;

assign S_AXIS_V_user_V_0_state_cmp_full = ((S_AXIS_V_user_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign S_AXIS_V_user_V_0_vld_in = S_AXIS_TVALID;

assign S_AXIS_V_user_V_0_vld_out = S_AXIS_V_user_V_0_state[1'd0];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign exitcond1_fu_404_p2 = ((i_reg_288 == 17'd65536) ? 1'b1 : 1'b0);

assign exitcond_fu_539_p2 = ((i_1_reg_355 == 17'd65536) ? 1'b1 : 1'b0);

assign grp_count_occ_v2_fu_366_ap_start = grp_count_occ_v2_fu_366_ap_start_reg;

assign grp_sort_occ_v2_fu_375_ap_start = grp_sort_occ_v2_fu_375_ap_start_reg;

assign i_4_fu_410_p2 = (i_reg_288 + 17'd1);

assign i_5_fu_545_p2 = (i_1_reg_355 + 17'd1);

assign indvarinc3_i_fu_488_p2 = (invdar2_i_reg_311 + 8'd1);

assign indvarinc6_i_fu_505_p2 = (invdar5_i_reg_322 + 8'd1);

assign indvarinc9_i_fu_522_p2 = (invdar8_i_reg_333 + 8'd1);

assign indvarinc_fu_387_p2 = (invdar_reg_277 + 16'd1);

assign indvarinc_i_fu_471_p2 = (invdar_i_reg_300 + 8'd1);

assign tmp_16_fu_441_p1 = i_reg_288;

assign tmp_17_fu_551_p1 = i_1_reg_355;

assign tmp_18_fu_556_p2 = ((i_1_reg_355 == 17'd65535) ? 1'b1 : 1'b0);

assign tmp_1_i_fu_494_p1 = invdar2_i_reg_311;

assign tmp_2_i_fu_499_p2 = ((invdar2_i_reg_311 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_3_i_fu_511_p1 = invdar5_i_reg_322;

assign tmp_4_i_fu_516_p2 = ((invdar5_i_reg_322 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_528_p1 = invdar8_i_reg_333;

assign tmp_6_i_fu_533_p2 = ((invdar8_i_reg_333 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_fu_393_p1 = invdar_reg_277;

assign tmp_i_16_fu_482_p2 = ((invdar_i_reg_300 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_i_fu_477_p1 = invdar_i_reg_300;

assign tmp_last_V_fu_562_p2 = (val_4_reg_344 | tmp_18_fu_556_p2);

assign tmp_s_fu_398_p2 = ((invdar_reg_277 == 16'd65535) ? 1'b1 : 1'b0);

endmodule //HLS_radix
